"""Replace QR system with AR claim system

Revision ID: e7983b2fa3d3
Revises: 
Create Date: 2026-02-09 14:22:05.291442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7983b2fa3d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # STEP 1: Drop foreign key constraints that reference qr_codes
    op.drop_constraint('rewards_qr_code_id_fkey', 'rewards', type_='foreignkey')
    
    # STEP 2: Drop scan_logs table (has FK to qr_codes)
    op.drop_index('ix_scan_logs_qr_code_id', table_name='scan_logs')
    op.drop_index('ix_scan_logs_user_id', table_name='scan_logs')
    op.drop_table('scan_logs')
    
    # STEP 3: Drop qr_codes table (now safe since no FKs reference it)
    op.drop_index('ix_qr_codes_code', table_name='qr_codes')
    op.drop_table('qr_codes')
    
    # STEP 4: Create new tables
    op.create_table('reward_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('reward_type', sa.String(length=20), nullable=False),
    sa.Column('reward_value', sa.Integer(), nullable=False),
    sa.Column('reward_description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_templates_location_id'), 'reward_templates', ['location_id'], unique=False)
    
    op.create_table('claim_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=500), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_logs_claimed_at'), 'claim_logs', ['claimed_at'], unique=False)
    op.create_index(op.f('ix_claim_logs_location_id'), 'claim_logs', ['location_id'], unique=False)
    op.create_index(op.f('ix_claim_logs_user_id'), 'claim_logs', ['user_id'], unique=False)
    
    # STEP 5: Update rewards table
    op.drop_column('rewards', 'qr_code_id')
    op.add_column('rewards', sa.Column('reward_template_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'rewards', 'reward_templates', ['reward_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewards', sa.Column('qr_code_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rewards', type_='foreignkey')
    op.create_foreign_key('rewards_qr_code_id_fkey', 'rewards', 'qr_codes', ['qr_code_id'], ['id'])
    op.drop_column('rewards', 'reward_template_id')
    op.create_table('scan_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('qr_code_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('device_fingerprint', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('scanned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='scan_logs_location_id_fkey'),
    sa.ForeignKeyConstraint(['qr_code_id'], ['qr_codes.id'], name='scan_logs_qr_code_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='scan_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='scan_logs_pkey'),
    comment='One scan per user per QR code enforced at app level + unique index'
    )
    op.create_index('ix_scan_logs_user_id', 'scan_logs', ['user_id'], unique=False)
    op.create_index('ix_scan_logs_qr_code_id', 'scan_logs', ['qr_code_id'], unique=False)
    op.create_table('qr_codes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('max_scans', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_scans', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reward_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('reward_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reward_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='qr_codes_location_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='qr_codes_pkey')
    )
    op.create_index('ix_qr_codes_code', 'qr_codes', ['code'], unique=True)
    op.drop_index(op.f('ix_reward_templates_location_id'), table_name='reward_templates')
    op.drop_table('reward_templates')
    op.drop_index(op.f('ix_claim_logs_user_id'), table_name='claim_logs')
    op.drop_index(op.f('ix_claim_logs_location_id'), table_name='claim_logs')
    op.drop_index(op.f('ix_claim_logs_claimed_at'), table_name='claim_logs')
    op.drop_table('claim_logs')
    # ### end Alembic commands ###
